# This is a basic workflow to help you get started with Actions

name: Newman-CLI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: mhalt/postman-collections/contactList_collection.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-api-tests.outputs.summary }}
